apiVersion: v1
kind: BuildConfig
metadata:
  name: aelsaman.inventory-management-ui-aelsaman
  labels:
    app: inventory-management-ui-aelsaman
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: 'https://github.com/aelsaman/inventory-management-ui-aelsaman.git'
      ref: master
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: dev-aelsaman
        - name: BRANCH
          value: master
